### ISSUE TITLE
can subprocess_join tell if the process failed?

### ISSUE THREAD

**Issue by pthom** [sheredom/subprocess.h#17]
Hello,

Thanks for this useful library!
I encountered a problem when calling subprocess_join: it cannot detect whether the process failed.

The following lines taken from the code show the reason:

````cpp
  if (out_return_code) {
    if (WIFEXITED(status)) {
      *out_return_code = WEXITSTATUS(status);
    } else {
      *out_return_code = 0  // process did not exit normally, but we return 0 as exit status, anyway (!)
    }
  }

````

Is there another way to check for process failures?

Thanks!

**Comment by sheredom** [comment]
Hey @pthom! Yeah that looks like a bug.

Do you have any small repro case for a process that doesn't exit 'normally'? I'm honestly not that sure how you can even get there (segfault or something?).

**Comment by sheredom** [comment]
Fixed by @pthom - thanks!
