### ISSUE TITLE
Binary is not found if the full path is not provided when using subprocess_create without environment options

### ISSUE THREAD

**Issue by JoseTomasTocino** [sheredom/subprocess.h#28]
In RHEL 7.3, when using `subprocess_create` with a `0` for the environment option, if I don't specify the full path of the binary, the call to [execvp fails and returns 255](https://github.com/sheredom/subprocess.h/blob/ae6f83d53672ea89d5f3d4077b405f0f0e85e036/subprocess.h#L615).

```
    const char * command_line[] = { "sleep", "10", NULL };

    struct subprocess_s subprocess;

    int result = subprocess_create(command_line, 0, &subprocess);

    if (0 != result)
    {
        std::cerr << "Error with subprocess" << std::endl;
    }

    int retcode = 0;
    
    result = subprocess_join(&subprocess, &retcode);
    
    if (0 != result)
    {
        std::cerr << "Error joining subprocess" << std::endl;
    }

    std::cout << "Ret code: " << retcode << std::endl; // This prints 255
```

However, if I use any environment option, like `subprocess_option_inherit_environment`, your lib [uses execve instead](https://github.com/sheredom/subprocess.h/blob/ae6f83d53672ea89d5f3d4077b405f0f0e85e036/subprocess.h#L613), which does need to have the full path. [Here's a better explanation for that behavior](https://stackoverflow.com/a/49226136/276451).

To my understanding, the behavior should be consistent in both cases.

**Comment by sheredom** [comment]
Yeah it should be consistent - good catch! Fancy doing a PR? Otherwise I'll get to this when I can 😄

**Comment by JoseTomasTocino** [comment]
Alright! Will try my best. Expect my PR.

**Comment by pathtofile** [comment]
Hi @JoseTomasTocino , I put up a PR as I also wouldn't mind the fix
