### ISSUE TITLE
Implement: bool subprocess_alive()

### ISSUE THREAD

**Issue by IngwiePhoenix** [sheredom/subprocess.h#33]
When working with an async process, it'd be nice to have a clean method to periodically check if the process is still alive or if it has already finished. Right now, `_join()`, `_destroy()` and `_terminate()` seem to all be about waiting for a process to end - or just destroying the struct and sending it away from the current process (as stated that `_destroy()` can leave a process running even after main execution has finished).

**Comment by sheredom** [comment]
I'll add this to the todo. PRs welcome though!
