### ISSUE TITLE
Support for "CREATE_NO_WINDOW" when launching process

### ISSUE THREAD

**Issue by BobbyAnguelov** [sheredom/subprocess.h#40]
Hi, 

Thanks for the great lib, it's saved me a lot of pain. Would it be able to add support for the 'CREATE_NO_WINDOW' creation flag for the windows CreateProcess call?

I've hacked it locally since I dont ever want the process windows to show up but it might be useful for others as well.

**Comment by sheredom** [comment]
Yeah that'd totally be doable. I can have a look at that this week!
