### ISSUE TITLE
Adding lifetime documentation

### ISSUE THREAD

**Issue by Qix-** [sheredom/subprocess.h#51]
Hey there, great little library. Thank you so much for releasing it!

There's something missing from the header's docs that would be immensely helpful for consumers: lifetime requirements of parameters.

For example, `subprocess_create_ex`'s environment array parameter - does the memory pointed to by the pointer value need to out-live the subprocess's? Or can that memory be freed directly after the call returns?

Adding that sort of information would be really helpful. :)

**Comment by sheredom** [comment]
Good shout! I'll add something 😄

**Comment by sheredom** [comment]
Fixed! https://github.com/sheredom/subprocess.h/commit/96ad0e1dc35c43581b46b8aa4509b9ecd11fda8e

**Comment by Qix-** [comment]
Thank you :)
