### ISSUE TITLE
MinGW support

### ISSUE THREAD

**Issue by takase1121** [sheredom/subprocess.h#58]
By default `subprocess.h` will not work on MinGW because of `_MSC_VER`.

I managed to get it to compile (and at least work (create, read stderr and join)) by:
- removing line 353 (definition for `_alloca`) and instead `#include <malloc.h>`
- `-D_MSC_VER=1920` (this should be replaced by `#ifdef _WIN32` and similiar
- `-D_DLL` as gcc doesn't like it when it tries to compare to something undefined.

**Comment by sheredom** [comment]
I don't support MinGW - if there was a way to test support for it in GitHub Actions I could consider it though.

**Comment by takase1121** [comment]
I can help with that, but I'm busy at the moment. Anyone interested can just take up the job in the meantime.

**Comment by sheredom** [comment]
Given I'm not intending on fixing this myself, and you don't have the time, I'm closing the issue.

Feel free to re-open if you get the chance to look at this (but I've personally no intention of ever working on MinGW support on Windows!)
