### ISSUE TITLE
Incorrect argument quoting on Windows

### ISSUE THREAD

**Issue by takase1121** [sheredom/subprocess.h#59]
Yeah. I'm also speechless. Apparently on Windows you **MUSTN'T** quote too little or too much.

```c
#include <stdio.h>
#include <stddef.h>
#include <malloc.h>
#include "subprocess.h"

int main() {
        const char *cmd[] = { "cmd", "/c", "echo hello", NULL };
        struct subprocess_s sub;
        int r = subprocess_create(cmd, 0, &sub);
        FILE *p = subprocess_stderr(&sub);
        char bruh[32];
        while (fgets(bruh, 32, p)) {
                printf("%s\n", bruh);
        }
        int pr;
        subprocess_join(&sub, &pr);
        return 0;
}
```

The code is a bit messy, but its obvious this is your typical run of the mill `echo` example adapted for Windows.
The only problem is it doesn't work.

Apparently `cmd.exe` **doesn't like its flags to be quoted**. This library quotes every argument, so something from the above example would produce `"cmd" "/c" "echo hello world"`. Perfectly fine for you and me (and sh), but for cmd... it interpreted `"/c" 
 "echo hello world"` as `/c "\"echo hello world"`! Suddenly there's an extra quote there. The solution is apparently
 ```c
const char *cmd[] = { "cmd", "/c echo hello", NULL };
```

This entire thing is just mind-boggling. 
Apparently [the gold standard][1]'s `force` parameter is actually important! The only way I see to fix this problem is to not quote unescaped parameter, but I am not entirely sure (also pretty hard to do).

EDIT: some potential fixes:
```diff
454a455
>   int need_quoting;
625,626c626,631
<     // For the ' ' and two '"' between items and trailing '\0'
<     len += 3;
---
>     // For the trailing \0
>     len++;
>
>     // Quote the argument if it has space or tabs in it
>     if (strpbrk(commandLine[i], "\t\v ") != NULL)
>       len += 2;
659c664,668
<     commandLineCombined[len++] = '"';
---
>
>     need_quoting = strpbrk(commandLine[i], "\t\v ") != NULL;
>     if (need_quoting) {
>       commandLineCombined[len++] = '"';
>     }
678c687,690
<     commandLineCombined[len++] = '"';
---
>
>     if (need_quoting) {
>       commandLineCombined[len++] = '"';
>     }
```

[1]: https://docs.microsoft.com/en-gb/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way

**Comment by sheredom** [comment]
Happy to accept a PR.

**Comment by aardappel** [comment]
Just ran into this as well.. weirdly, quoting `"/c"` directly on the command line works, but not when run from `CreateProcessA` ?

**Comment by takase1121** [comment]
> Just ran into this as well.. weirdly, quoting `"/c"` directly on the command line works, but not when run from `CreateProcessA` ?

That's because the quotes are intepreted by `cmd`/`powershell` and removed because there's no space in it.
