### ISSUE TITLE
posix_spawn does not build on Android & Emscripten (Wasm)

### ISSUE THREAD

**Issue by aardappel** [sheredom/subprocess.h#66]
The changes introduced here https://github.com/sheredom/subprocess.h/commit/de3cbecd06d5a631e74ec6e77d03ec466d861726 produce compilation errors on these two platforms: https://github.com/aardappel/lobster/actions/runs/2278815862

Now I am totally fine #ifdeffing support out for those 2 platforms, since it doesn't make any sense to spawn processes there anyway. But the curious thing is that the old fork code DID compile on those platforms.

So it is more of a question if you want to #ifdef it in your library for maximum modularity, or if you want users to #ifdef it :) I don't mind either way. Feel free to close if WillNotFix.

**Comment by sheredom** [comment]
I think I'd want users to #ifdef it - given that subprocess spawning doesn't work on those platforms anyway I don't see much of the point!
